# Generated by Django 5.2.5 on 2025-08-31 20:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Formulario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=250, verbose_name="Nome Completo"),
                ),
                ("email", models.CharField(max_length=100, verbose_name="E-Mail")),
                (
                    "data_de_nascimento",
                    models.DateField(verbose_name="Data de Nascimento"),
                ),
                (
                    "senha",
                    models.CharField(
                        max_length=20,
                        validators=[django.core.validators.MinLengthValidator(5)],
                        verbose_name="Senha",
                    ),
                ),
            ],
        ),
    ]
