# Generated by Django 5.2.5 on 2025-08-31 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("formulario", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Formulario",
            new_name="Usuario",
        ),
    ]
